In [3]:
import numpy as np

In [31]:
train_data=np.array([[0],[10],[20],[30],[40],[50],[60]])

In [32]:
from sklearn.preprocessing import MinMaxScaler

In [33]:
sc=MinMaxScaler()

In [34]:
train_data=sc.fit_transform(train_data)

In [35]:
train_data

array([[0.        ],
       [0.16666667],
       [0.33333333],
       [0.5       ],
       [0.66666667],
       [0.83333333],
       [1.        ]])

In [15]:
test_data=np.array([[40],[50],[10]])

In [23]:
test_data= sc.fit_transform(test_data)

In [24]:
test_data

array([[0.75],
       [1.  ],
       [0.  ]])

In [ ]:
# why we do only transform, bcoz using fit will make it calculate the values again and will change them
# to avoid recalculating


In [36]:
test_data=np.array([[40],[50],[10]])

In [37]:
test_data= sc.transform(test_data)

In [38]:
test_data

array([[0.66666667],
       [0.83333333],
       [0.16666667]])

In [39]:
# fit means to learn from data

In [40]:
#we can also use fit to train data and then transform for both test and train data

In [45]:
train_data=np.array([[0],[10],[20],[30],[40],[50],[60]])

In [46]:
from sklearn.preprocessing import MinMaxScaler

In [47]:
sc.fit(train_data)

MinMaxScaler()

In [48]:
train_data=sc.transform(train_data)

In [49]:
train_data

array([[0.        ],
       [0.16666667],
       [0.33333333],
       [0.5       ],
       [0.66666667],
       [0.83333333],
       [1.        ]])

In [51]:
test_data=np.array([[40],[50],[10]])
test_data=sc.transform(test_data)

In [52]:
test_data

array([[0.66666667],
       [0.83333333],
       [0.16666667]])